### PR TITLE
To Do list: interactive list

### PR DESCRIPTION
**Pull request by nahnahdev**
## Project requirements

- [ ]  Add a new JavaScript file and import it as a module:
- [ ]         it will contain methods related to the status updates (completed: `true / false`).
- [ ]     Add event listener to the checkbox (change).
- [ ]     Update items object's value for completed key upon user actions.
- [ ]     Implement a function for the "Clear all completed" button (use filter() method).
- [ ]     Store the updated array of items in local storage, so the user gets the correct list values after the page reloads.

### CODE REVIEW

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @NahnahAJ, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used
✔️  Good PR title and Description



## Required Changes ♻️

- [ ] Please ensure that your app is functioning properly, I cannot add a new todo, Kindly work on this feature of the  application as it is needed to test the app properly, see project [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md#project-requirements) and video below ⬇️ 

https://user-images.githubusercontent.com/69638013/193425122-3b301e25-d30d-40d3-9a47-4d7248e44ae9.mp4


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NahnahAJ** [comment]
> Hi @NahnahAJ, Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> ✔️ No linter errors ✔️ Git flow was correctly used ✔️ Good PR title and Description
> 
> ## Required Changes ♻️
> * [ ]  Please ensure that your app is functioning properly, I cannot add a new todo, Kindly work on this feature of the  application as it is needed to test the app properly, see project [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md#project-requirements) and video below ⬇️
> 
>  Loom.Message.-.1.October.2022.mp4 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
> * N/A
>   Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

He

**Comment by nahnahdev** [comment]
Hello @prolajumokeoni I checked on your comment but the app works fine on my end I also sent it out to colleagues and they confirmed that it is working. So I am not sure what the problem is. I have attached a loom video link below.

https://www.loom.com/share/348a3a09bfcf4e6583d8286cc4b6bce3

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @NahnahAJ, 

# Required Changes ♻️
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 
- Good communication with code reviewer 💯 


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] I have cloned your repository but I could not add activities to the list 👇🏽. 

https://user-images.githubusercontent.com/58642949/193427363-aed8ff4b-a3c6-45a1-8185-3aaebcbc2130.mp4

As the last code reviewer said:

>  Please ensure that your app is functioning properly, I cannot add a new todo, Kindly work on this feature of the application as it is needed to test the app properly, see project [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md#project-requirements) and video below ⬇️


https://user-images.githubusercontent.com/58642949/193427248-2f327e82-5ccc-4778-842b-98e0acd576d9.mp4


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mgmediaweb — APPROVED** [review]
Hi @NahnahAJ, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

approved5

## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
